---
title: "{{{ title }}}"
author: "{{{ author }}}"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: 
      collapse : false
    toc_depth: 3
    # code_folding: hide
    number_sections: true
    # css: styles.css
# bibliography: citations_in_report.bib
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding= encoding, output_dir= "../reports") })
---

```{r, echo=FALSE, include=FALSE}
## Chunk hooks
knitr::knit_hooks$set(
  optipng = knitr::hook_optipng   # Ready to activate optipng (Optimize PNG)
)
## Set default chunk options
knitr::opts_chunk$set(
	echo = FALSE,    # comment out for code_folding
	# dev = c('pdf'), fig.path = '../results/figures/', # export figures to pdf files
  results = "asis",   # for HTML
  message = FALSE,    # no message from the code
  warning = FALSE,    # no warning from the code
	cache.path = "../cache/",   # cache the results from heavy analyses
	fig.width  = 8,
  fig.height = 6,
	eval.after = "fig.cap",    # to add fig. caption within the chunk
  optipng = '-o1', # '-o7 -zc9 -zm8 -zs0', # Optimize 'png' plots
	purl = FALSE      # because most of the code are not to be extracted
)
options(knitr.kable.NA = '')  # NA is shown as ''
```

```{r, echo=FALSE, include=FALSE, purl=TRUE}
## Pre-loaded packages
# Please note that some functions are called directly from the package using
# double-colon '::' or triple-colon ':::' to make the source clearer.
library(tidyverse)
library(kableExtra)
library(janitor)
library(lme4)       # lme4::predict for class `merMod`
library(foreach)  # %dopar%, foreach
```

```{r, purl=TRUE}
rm(list = ls())

## File names
fn <- list(
  lib = "utils.R",
	i = list(                               # input
    # olk02 = "../data/s1-olink_proteomic.v02.RData", 
    # c01 = "../data/s1-clinical.v01.RData"
	)
)

# Brief check if all files exist
stopifnot(all(file.exists(fn$lib, unlist(fn$i))))
# # Warn any difference in input file(s) using MD5 hash
# if(!all(
#   tools::md5sum(fn$i$file1) == "MD5_hash"
# )) warning(
#   "One input file or more is not exactly identical to the one used during ",
#   "development of this script."
# )

source(fn$lib)  # geom_split_violin, add_n

# # Load proteomic data ver.02
# load(fn$i$olk02)
# # Load clinical information ver.01
# load(fn$i$c01)
```

# Chapter

## Quality control


----------------------------



----------------------------

# Appendix

## Methods

_short texts about the methods_

Bioinformatic data handling and statistic analyses were done on `r R.version.string`, 
together with tidyverse (v. `r packageVersion("tidyverse")`) package.

## R environment

```{r sessionInfo, results='markup'}
sessionInfo()
```
